ALTER TABLE tapes
    ALTER COLUMN density_code TYPE VARCHAR(255),
    ALTER COLUMN medium_type TYPE VARCHAR(255),
    ALTER COLUMN manufacturer TYPE VARCHAR(255),
    ALTER COLUMN assigning_org TYPE VARCHAR(255),
    ALTER COLUMN medium_type_info TYPE VARCHAR(255);
ALTER TABLE submissions
    ALTER COLUMN tape_alert_flags TYPE VARCHAR(255),
    ALTER COLUMN assigning_org TYPE VARCHAR(255),
    ALTER COLUMN barcode TYPE VARCHAR(255);
